"all":
  "children":
    "almalinux":
      "hosts":
        "gitea":
          "ansible_host": "10.37.80.4"
          "ansible_user": "root"
          "system_hostname": null
        "truenas-proxy":
          "ansible_host": "10.37.70.42"
          "ansible_user": "root"
          "system_hostname": null
